version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: sdp_postgres
    environment:
      POSTGRES_USER: sdp
      POSTGRES_PASSWORD: sdp_password
      POSTGRES_DB: sdp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ingestion_api:
    build:
      context: ../server/ingestion_api
      dockerfile: Dockerfile
    container_name: sdp_ingestion_api
    depends_on:
      - postgres
    environment:
      SDP_ENV: dev
      DB_DSN: postgresql://sdp:sdp_password@postgres:5432/sdp
      SDP_CRYPTO_KEY: "Miql-SH11OTpm4rFOh5QF7iNG2fPolSwwvvb1YceREw="
    ports:
      - "8081:8080"    # host:container
    restart: unless-stopped

volumes:
  postgres_data:
